import numpy as np

segments_dtype = np.dtype([("eventID", "u4"),
                           ("segment_id", "u4"),
                           ("trackID", "u4"),
                           ("tran_diff", "f4"),
                           ("n_electrons", "u4"),
                           ("pdgId", "i4"),
                           ("t0_start", "f8"),
                           ("t0_end", "f8"),
                           ("t0", "f8"),
                           ("dx", "f4"),
                           ("long_diff", "f4"),
                           ("pixel_plane", "i4"),
                           ("t_end", "f4"),
                           ("dEdx", "f4"),
                           ("dE", "f4"),
                           ("y", "f4"),
                           ("x", "f4"),
                           ("z", "f4"),
                           ("t", "f4"),
                           ("x_start", "f4"),
                           ("y_start", "f4"),
                           ("z_start", "f4"),
                           ("t_start", "f4"),
                           ("x_end", "f4"),
                           ("y_end", "f4"),
                           ("z_end", "f4"),
                           ("n_photons","f4")],
                          align=True)

trajectories_dtype = np.dtype([("eventID", "u4"),
                               ("trackID", "u4"),
                               ("parentID", "i4"),
                               ("pxyz_start", "f4", (3,)),
                               ("xyz_start", "f4", (3,)),
                               ("t_start", "f4"),
                               ("pxyz_end", "f4", (3,)),
                               ("xyz_end", "f4", (3,)),
                               ("t_end", "f4"),
                               ("pdgId", "i4"),
                               ("start_process", "u4"),
                               ("start_subprocess", "u4"),
                               ("end_process", "u4"),
                               ("end_subprocess", "u4")],
                              align=True)

vertices_dtype = np.dtype([("eventID","u4"),
                           ("x_vert","f4"),
                           ("y_vert","f4"),
                           ("z_vert","f4")],
                          align=True)
